apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-{{ template "preferences.name" . }}
  labels:
    app: {{ template "preferences.name" . }}
spec:
  acme:
    server: {{ .Values.acme.server }}
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ template "preferences.name" . }}
    dns01:
      providers:
      - name: default
        clouddns:
          project: {{ required "A valid GCP Project id required for acme.clouddnsProject!" .Values.acme.clouddnsProject }}
